---
main:
  - name: BLOG
    url: blog/
    pre: <i class='fas fa-terminal'>&nbsp;</i>
    weight: 20
  - name: ' ABOUT ME'
    url: about/
    weight: 30
    identifier: about
    pre: <i class='far fa-address-card'>&nbsp;</i>
  - name: PROJECTS
    url: projects/
    weight: 50
    pre: <i class='fas fa-code-branch'>&nbsp;</i>
  - name: ' GARDEN'
    url: garden/
    weight: 60
    identifier: garden
    pre: <i class='fas fa-tree'>&nbsp;</i>
  - name: ' FANTASY'
    url: fantasy/
    weight: 70
    identifier: fantasy
    pre: <i class='fas fa-football-ball'>&nbsp;</i>
  - name: ''
    url: 'tags/'
    weight: 80
    pre: <i class='fas fa-tags'>&nbsp;</i>
    identifier: tags
  - name: ''
    url: 'categories/'
    weight: 85
    pre: <i class='fas fa-th-large'>&nbsp;</i>
    identifier: cats
  - name: ''
    url: 'https://follow.it/luiscachog-io'
    weight: 90
    pre: <i class='fas fa-rss'>&nbsp;</i>
    identifier: rss
